# -*- coding: utf-8 -*-
u"""A place to say what you found.                                                       2026-10-01

Gary: *"Do you think we should include a separate space where users can make suggestions for new
features, log bug reports, or even discuss interesting findings they've noticed?"*
Søren: *"I think we should do one forum for each jump."* and *"I don't see the Discussion anywhere?
Can we build it now?"*

core/forum.js is the forum; this puts it on the page. A fifth tab beside References, a card for it
to fill, and the one call that fills it.

µJUMP ONLY, FOR NOW, and the reason is in the PAGES comment below: the six hand-maintained pages do
not share a tab-bar shape, and a Discussion button on a page with no panel behind it is worse than
no button. µJump is the page in front of him and the only one whose nucleus table the links resolve
against.

A FIFTH TAB RATHER THAN A CARD AT THE BOTTOM. The tab bar already exists on every hand-maintained
page and already has four, so this costs no layout and nothing to anybody who ignores it — whereas
a card at the foot of the Jump tab would sit under the thing people came to use and be seen by
nobody, or sit above it and be in the way of everybody.

FILLED WHEN IT IS FIRST OPENED, NOT ON LOAD. The forum is one more request to the backend, and a
page nobody has clicked Discussion on should not pay for it. The tab engine already fires an event
when a panel is shown; this listens for it once.

WHAT IT IS CALLED. "Discussion", not "Forum": a forum is a place you go to, and this is a thing you
do about what is in front of you. Søren's own word, from the plan he approved.

WHERE THE TWO STREAMS COME FROM is core/forum.js's and the backend's business, not this file's.
This file knows one thing the module cannot: which tool it is, which the tools stream records so
that a bug reported in ωJump still says ωJump when it is read in µJump.

Check: forumcheck.js.
Run: python3 src/a_place_to_say_what_you_found.py, then python3 src/build_stamps.py
"""
import io, os
HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# ── µJUMP FIRST, AND ONLY µJUMP ────────────────────────────────────────────────────────────────
# The six hand-maintained pages do NOT share a tab-bar shape: µJump, δJump and πJump name the
# dashboard tab "dashboard", ηJump calls it "dash", and λJump and βJump call their references tab
# "references" rather than "refs". Their data blocks differ too, so the panel anchor that is unique
# in three of them does not exist in the other three.
#
# One generator pretending otherwise would either assert its way out on page four -- leaving the
# first three edited and the rest not, which edit() does atomically per file but not across files
# -- or, worse, match something loosely and put a Discussion button on a page with no panel behind
# it. A tab that does nothing is a worse answer than no tab.
#
# So: µJump, which is the page Søren is looking at and the only one with the nucleus table the
# links resolve against anyway. The other five, ωJump (which inlines core/) and χJump (generated by
# build_xjump.py) follow once the shape here has been seen working.
PAGES = [("ujump.html", "ujump", "minnie65")]


def edit(rel, pairs):
    P = os.path.join(HERE, rel)
    if not os.path.exists(P):
        print("  (no %s)" % rel); return
    s = io.open(P, encoding="utf-8").read(); b = s
    print(rel)
    for name, old, new in pairs:
        if new in s:
            print("  already there: " + name); continue
        n = s.count(old); assert n == 1, "%s (%s): %d" % (name, os.path.basename(P), n)
        s = s.replace(old, new, 1); print("  ok: " + name)
    if s != b: io.open(P, "w", encoding="utf-8").write(s)


TAB_OLD = u'<button type="button" class="tabbtn" data-tab="dashboard"'
TAB_NEW = (u'<button type="button" class="tabbtn" data-tab="forum" role="tab" aria-selected="false"'
           u' title="Findings, bugs and ideas. Coordinates and ids written into a post become links'
           u' — a reader opens exactly what you saw.">\U0001f4ac Discussion</button>\n'
           u'<button type="button" class="tabbtn" data-tab="dashboard"')

PANEL_OLD = u'</div>\n</div>\n<script type="application/json" id="nucdata">'
PANEL_TMPL = (u'</div>\n</div>\n'
              u'<!-- ── DISCUSSION ── 2026-10-01. The panel is empty markup; everything in it is\n'
              u'     core/forum.js\'s, exactly as the tracing card works. Filled the first time the\n'
              u'     tab is opened rather than on load: it is one more request to the backend, and a\n'
              u'     page nobody has clicked Discussion on should not pay for it. -->\n'
              u'<div class="tabpanel" data-tabpanel="forum">\n'
              u'<div id="forumCard"></div>\n'
              u'</div>\n'
              u'<script>\n'
              u'(function(){\n'
              u'  var started=false;\n'
              u'  function openForum(){\n'
              u'    if(started)return; started=true;\n'
              u'    if(window.UJ&&UJ.forum)UJ.forum.init({tool:%(tool)s,volume:%(vol)s});\n'
              u'  }\n'
              u'  /* The tab engine switches panels by toggling .active on [data-tabpanel]; there is\n'
              u'     no event to listen for, so this watches the button that opens it. Clicking the\n'
              u'     tab is the only way in, and a second click must not re-read the forum — hence\n'
              u'     `started`, and the Refresh is inside the card rather than out here. */\n'
              u'  var btn=document.querySelector(\'#mainTabs .tabbtn[data-tab="forum"]\');\n'
              u'  if(btn)btn.addEventListener("click",openForum);\n'
              u'})();\n'
              u'</script>\n'
              u'<script type="application/json" id="nucdata">')

SCRIPT_OLD = u'<script src="core/jumplink.js"></script>'
SCRIPT_NEW = (u'<script src="core/jumplink.js"></script>\n'
              u'<!-- The Discussion tab: findings, bugs and ideas, with the places a post names made\n'
              u'     clickable by core/jumplink.js above. 2026-10-01. -->\n'
              u'<script src="core/forum.js"></script>')

for page, tool, vol in PAGES:
    P = os.path.join(HERE, page)
    if not os.path.exists(P):
        print("  (no %s)" % page); continue
    s = io.open(P, encoding="utf-8").read()
    # The panel anchor is ujump's; the other pages carry their own data block, so the anchor is
    # found per page rather than assumed. A page whose shape does not match is reported, not
    # silently skipped: a Discussion tab with no panel is a button that does nothing.
    panel_old = PANEL_OLD if PANEL_OLD in s else None
    if panel_old is None:
        for cand in [u'</div>\n</div>\n<script type="application/json" id="',
                     u'</div>\n</div>\n<script type="application/json"']:
            if s.count(cand) == 1:
                panel_old = cand; break
    assert panel_old, "no panel anchor in %s" % page
    panel_new = PANEL_TMPL.replace(
        u'<script type="application/json" id="nucdata">', panel_old.split(u"\n", 2)[2]
    ) % {"tool": u'"%s"' % tool, "vol": u'"%s"' % vol}
    edit(page, [
        (u"a Discussion tab", TAB_OLD, TAB_NEW),
        (u"...with a panel for it", panel_old, panel_new),
        (u"...and the module that fills it", SCRIPT_OLD, SCRIPT_NEW),
    ])

print("\nNow: node forumcheck.js, then python3 src/build_stamps.py")
