"""Generate core/blenderexport.js from the notebook that is already tested.        2026-09-07

Søren: "I think it looks good now, we are ready for implementing."

── THE DESIGN DECISION, WHICH IS THE WHOLE FILE ──────────────────────────────────────────────

The obvious way to give the bounding-box panel a Blender export is to write a second JavaScript
notebook generator next to core/colabexport.js -- a few hundred lines of Python-inside-JS template
strings, built by hand, tested by running it.

This does NOT do that, because there is already a notebook: blender/ujump_blender_scene.ipynb,
generated by make_colab_notebook.py, embedding four Python modules verbatim, and covered by four
check suites (emplancheck, emfetchcheck, notebookcheck, blendscenecheck). A hand-written JS twin
would be a SECOND definition of the same pipeline, and the two would drift -- silently, because
only one of them has checks.

So core/blenderexport.js carries THE TESTED NOTEBOOK, verbatim, as data, and replaces exactly one
cell: the one tagged "params", which is the cell holding everything the panel decides --

    INCLUDE           the four checkboxes
    CELLS             the Filter-and-show matches inside this box, with their nucleus IDs
    COLORS            the palette, per cell type
    EM / SEG / NUC    the dataset's own source paths, from UJ.cfg.em
    the caps          EM_MAX_PX / EM_MAX_SECTIONS / EM_MAX_MB / OVERLAY_OPACITY
    the box           EM_BOX_MODE = 'manual' and EM_BOX_UM, in dataset micrometres

Every other cell arrives at Colab byte-identical to the one this repository tests. That is the
property worth having, and it is why the file is generated rather than written.

The cost is size: the notebook is ~120 KB of JSON and it is embedded whole. ujump.html loads it
as an ordinary <script>, the way it already loads core/colabexport.js. Worth revisiting if the
page ever gets weight-conscious -- a lazy inject on first click would work -- but not worth the
extra failure mode today.

── WHAT THE PANEL HAS TO SUPPLY ──────────────────────────────────────────────────────────────

opts, mirroring core/colabexport.js's shape so the two buttons read alike:

    {datasetId, datasetLabel, emSource, segSource, nucSource,
     boxNM: {xmin,xmax,ymin,ymax,zmin,zmax},      physical nanometres, as colabexport uses
     boxLabel: "Box 1",
     cells: [{type, root_id, nucleus_id}],        the matches inside THIS box
     include: {em, seg, meshes, nuclei}}

   NO COLOURS. blend_scene.py's cell_colours() decides them from the scene -- one cell in the
   tool's accent, several in one palette colour each, nuclei always blue, vessels always red.
   See src/scene_colour_policy.py for why that moved.

Run: python3 src/core_blenderexport.py
"""
import io
import json
import os

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
NB_PATH = os.path.join(HERE, "blender", "ujump_blender_scene.ipynb")
OUT = os.path.join(HERE, "core", "blenderexport.js")

nb = json.load(io.open(NB_PATH, encoding="utf-8"))
tagged = [c for c in nb["cells"] if c.get("metadata", {}).get("ujump") == "params"]
assert len(tagged) == 1, "expected exactly one params cell, found %d" % len(tagged)

# Embedded as a JSON string literal rather than as an object literal: JSON.parse of a string is
# faster than evaluating a 120 KB object literal, and the escaping rules are simpler to get right.
NB_JSON = json.dumps(json.dumps(nb, ensure_ascii=False))

JS = '''/* core/blenderexport.js -- GENERATED by src/core_blenderexport.py. Do not edit by hand.

   Søren, 2026-09-06: "There should be an option to select download Blender file and then you
   download this code." So the bounding-box panel's button writes THIS notebook instead of the
   EM/segmentation one when "Blender file" is ticked.

   ── WHY THIS FILE IS GENERATED ──────────────────────────────────────────────────────────────

   It carries blender/ujump_blender_scene.ipynb verbatim, as data, and replaces exactly one cell
   -- the one tagged "params" -- with the panel's own values. Every other cell reaches Colab
   byte-identical to the notebook this repository tests with emplancheck (15), emfetchcheck (23),
   notebookcheck (14) and blendscenecheck (18).

   The alternative was a hand-written JavaScript twin of make_colab_notebook.py. That would be a
   second definition of the same pipeline, and the two would drift -- silently, because only one
   of them would have checks. Re-run the generator after editing any of blend_scene.py,
   glb_write.py, em_plan.py, em_fetch.py or make_colab_notebook.py.

   ── WHAT THE NOTEBOOK DOES, IN ONE PARAGRAPH ────────────────────────────────────────────────

   Fetches the matched cells' meshes and their nuclei, plans an EM (and segmentation) cutout for
   the box against the source's own scale ladder and REFUSES a box no available level can bring
   under the caps, writes the sections as PNGs with the matched cells painted over them, writes a
   .glb in pure Python, then -- best effort -- downloads Blender and builds a .blend with a
   three-act animation: the sections run out with no models drawn, back with them in place, then
   the camera pulls back and turns. Ctrl+F12 renders an MP4.

   Public surface: UJ.blender.buildNotebook(opts), UJ.blender.downloadNotebook(opts).
*/
window.UJ = window.UJ || {};
UJ.blender = (function(){
  "use strict";

  /* The tested notebook, whole. */
  const NB_SOURCE = %s;

  /* Jupyter writes `source` as an array of lines each ending in "\\n" except the last; a single
     joined string also works in most readers, but matching the real convention avoids surprises
     in stricter parsers. Same helper, same reason, as core/colabexport.js. */
  function srcLines(s){
    const lines = String(s).split("\\n");
    return lines.map((l, i) => i < lines.length - 1 ? l + "\\n" : l);
  }

  /* SINGLE-QUOTED where it is safe, because every other line of Python in this notebook is, and
     a params cell that mixes 'type': "23P" reads like it was pasted together by two people. Falls
     back to JSON.stringify -- double quotes, full escaping -- for anything carrying a quote, a
     backslash or a newline; a cell type is free text and could in principle carry any of them.

     The risky characters are built with fromCharCode rather than written as escapes, because this
     file is itself generated and a backslash here has to survive two levels of quoting. It did
     not, once: the character class came out with a real newline in it and the whole module failed
     to parse with "Invalid regular expression: missing /". */
  const PY_RISKY = ["'", String.fromCharCode(92), String.fromCharCode(10), String.fromCharCode(13)];
  function pyStr(s){
    const v = String(s);
    return PY_RISKY.some(ch => v.indexOf(ch) >= 0) ? JSON.stringify(v) : "'" + v + "'";
  }
  function pyBool(v){ return v ? "True" : "False"; }
  function pyNum(n){ return Number.isFinite(n) ? String(n) : "0"; }

  /* gs:// and precomputed:// both reach cloud-volume unchanged; "middleauth+" is a Neuroglancer
     FRONTEND convention its Python reader does not want. Stripped here for the same reason
     core/colabexport.js strips it. */

  /* ── THE TOOL'S OWN COLOURS, READ OFF THE PAGE ─────────────────────────── 2026-09-08 ──────
     Søren: "the segmentation looks like it is colored after µJump instead of xJump." It was:
     every caller hand-built this block with accent "#27e0b3", µJump's teal, copied into four
     other pages and this module. They do not share a palette -- χJump is #4ade80, πJump #f78ad4,
     δJump #b388ff, ωJump #fbbf24 -- so every video was signed in the wrong tool's colour.

     THE DARK VALUES, whatever theme the page is showing, because the render's background is the
     dark one either way. The base `:root` rule is the dark theme on every page in this family
     (light is an override, under a prefers-color-scheme media query or [data-theme="light"]), so
     that rule is read directly rather than the computed style, which would follow the user. */
  function rootVar(name, fallback){
    /* THE LAST DECLARATION WINS, which is what a cascade is. Søren, 2026-09-09: "I don't want all
       of them to look like uJump's color theme." Every page in this family opens with µJump's
       palette and overrides it hundreds of lines later with its own -- βJump's #ff6b81 at line
       367, λJump's #7aa2ff, ηJump's #ffb454 -- and this loop used to RETURN on the first match,
       which is the inherited teal. The tools that were right (χ, δ, π) were right by file order.

       Per PROPERTY, not per rule: the late block redeclares only the accent trio, so --ink and
       --mut still have to come from the base one. */
    var found = "";
    try {
      for (var i = 0; i < document.styleSheets.length; i++){
        var rules;
        try { rules = document.styleSheets[i].cssRules; } catch (e) { continue; }  // cross-origin
        for (var j = 0; j < rules.length; j++){
          var r = rules[j];
          if (r.selectorText === ":root" && r.style){
            var v = String(r.style.getPropertyValue(name) || "").trim();
            if (v) found = v;                      // keep going: a later rule overrides this one
          }
        }
      }
      if (found) return found;
    } catch (e) {}
    /* The computed value is the CURRENT theme's, so it is the fallback rather than the answer:
       right in dark mode, and a light accent on a dark render is exactly what this avoids. */
    try {
      var c = getComputedStyle(document.documentElement).getPropertyValue(name).trim();
      if (c) return c;
    } catch (e) {}
    return fallback;
  }

  /* What signs the bottom-right corner of the video: the tool's wordmark, its site, the dataset
     credit, and the three colours those are drawn in. One function, so the five callers that used
     to build it by hand cannot disagree again. */
  function brandFromPage(){
    var logoEl = document.querySelector("h1.logo");
    return { name: (logoEl ? logoEl.textContent : "").trim()
                   || ((window.UJ && UJ.cfg && UJ.cfg.id) || ""),
             url: "www.grubblab.com",
             dataset: (window.UJ && UJ.cfg && (UJ.cfg.datasetCredit || UJ.cfg.label)) || "",
             accent: rootVar("--accent", "#27e0b3"),
             ink: rootVar("--ink", "#e6edf3"),
             mut: rootVar("--mut", "#8b949e") };
  }

  function toCloudVolumePath(src){ return String(src||"").replace("middleauth+", ""); }

  /* THE ONE CELL THE PANEL WRITES. Everything it contains is a decision made in the browser:
     which cells matched, what was ticked, where the box is. Everything else in the notebook is
     the pipeline, and arrives verbatim. */
  function paramsCell(opts){
    const inc = opts.include || {};
    /* `group` and `cell_name` are optional and exist for ONE dataset shape: χJump, where a cell
       is ASSEMBLED from fragments and arrives as thirty root ids that are all one cell. Without
       them the colour rule paints that cell in thirty colours (Søren, 2026-09-08: "This is one
       cell with many fragments, will it produce one cell of the same color or one cell of many
       colors?"). Every other tool leaves them undefined and colour_policy.py falls back to the
       root id, which is what a cell is there. */
    const cells = (opts.cells || []).map(c => ({
      type: String(c.type || "Unclassified"),
      root_id: String(c.root_id),
      nucleus_id: c.nucleus_id == null ? null : String(c.nucleus_id),
      group: c.group == null ? null : String(c.group),
      cell_name: c.cell_name == null ? null : String(c.cell_name)
    }));
    /* ── NO COLOURS ARE SENT ── 2026-09-08 ────────────────────────────────────────────────
       This block used to derive them: a 30-entry palette, by type when there was more than one
       type and per cell when there was not. It is gone, and the reason is a picture Søren sent.

       A box round an arteriole matched seven cells, all of them "Smooth muscle cell", so the type
       rule painted all seven #8a3b2a -- and the vessel they wrap is #b03a48. Two dark reds, both
       translucent, one inside the other. He had ticked Vasculature, the notebook fetched it, the
       scene contained it, and his report was "it was never shown": there was nothing to tell
       apart. Søren: "When there is only one cell ... the same color as the tool ... When there is
       more than one cell they should have different colors ... The vasculature, however, should
       always be red and the nucleus always blue."

       That is a rule about the whole scene -- how many cells there are, and which colours are
       reserved -- so it belongs to the thing that builds the scene. blend_scene.py's
       cell_colours() owns it now, and this cell sends none, because a caller that also sends
       colours is a second opinion that will disagree eventually. */
    const b = opts.boxNM || {};
    /* NANOMETRES IN, MICROMETRES OUT. The panel works in nm because that is what
       core/colabexport.js standardised on; em_plan.py takes dataset micrometres, the same units
       the meshes come back in. One division, in one place, named. */
    const um = v => Number(v) / 1000.0;
    const box = "((" + [um(b.xmin), um(b.ymin), um(b.zmin)].map(pyNum).join(", ") + "), ("
                     + [um(b.xmax), um(b.ymax), um(b.zmax)].map(pyNum).join(", ") + "))";

    const lines = [];
    lines.push("# Written by " + (opts.datasetLabel || opts.datasetId || "the tool")
               + "'s bounding-box panel -- " + (opts.boxLabel || "box") + ".");
    lines.push("# Every other cell in this notebook is the tested pipeline, unchanged.");
    lines.push("");
    lines.push("INCLUDE = {");
    lines.push("    'em':            " + pyBool(inc.em !== false) + ",");
    lines.push("    'segmentation':  " + pyBool(inc.seg !== false) + ",");
    lines.push("    'cell_3d_model': " + pyBool(inc.meshes !== false) + ",");
    /* A DATASET WITHOUT A NUCLEUS SOURCE CANNOT HAVE NUCLEI, whatever the tick says. Only
       minnie65 publishes one in this family, and `nucSource` is empty everywhere else -- so the
       source, not the checkbox, has the last word. The notebook guards this again on its own
       side; two guards because a silently-empty nucleus step looks exactly like a cell with no
       nucleus in the detection table. */
    lines.push("    'nuclei':        " + pyBool(inc.nuclei !== false && !!opts.nucSource) + ",");
    /* Vasculature: Wan & Wei's TriSAM segmentation, cut to this box and surfaced. Defaults ON
       like the rest -- the panel tick is what turns it off -- and the notebook's own cell is
       written so that a failure here (source unreachable, box outside the volume) prints and
       carries on rather than costing the whole run. */
    lines.push("    'vasculature':   "
               + pyBool(inc.vasc === true && !!(opts.vascSource || opts.canVasc)) + ",");
    lines.push("}");
    lines.push("");
    lines.push("CELLS = [");
    cells.forEach(c => {
      lines.push("    {'type': " + pyStr(c.type) + ", 'root_id': " + pyStr(c.root_id)
                 + ", 'nucleus_id': " + (c.nucleus_id ? pyStr(c.nucleus_id) : "None")
                 + (c.group ? ", 'group': " + pyStr(c.group) : "")
                 + (c.cell_name ? ", 'cell_name': " + pyStr(c.cell_name) : "") + "},");
    });
    lines.push("]");
    lines.push("");
    /* EMPTY, and it has to exist: the notebook's manifest cell writes 'colors': COLORS, and a
       name this cell does not set is a NameError. blend_scene.py reads an empty map as "no
       explicit colours were asked for" and applies the policy -- one cell in the tool's accent,
       several in one palette colour each, nuclei blue, vessels red. */
    lines.push("# Empty on purpose: blend_scene.py decides the colours (see cell_colours there).");
    lines.push("# A colour named here would OVERRIDE that, which is what a hand-edited manifest");
    lines.push("# is for -- put {'Astrocyte': '#40e28c'} here to pin one type.");
    lines.push("COLORS = {}");
    lines.push("");
    lines.push("EM  = " + pyStr(toCloudVolumePath(opts.emSource)));
    lines.push("SEG = " + pyStr(toCloudVolumePath(opts.segSource)));
    lines.push("NUC = " + pyStr(toCloudVolumePath(opts.nucSource || "")));
    /* ── THE ONE AUTHENTICATED DATASET ────────────────────────────────────────────────────
       V1DD's segmentation is graphene://middleauth+..., a live CAVE service: the imagery is
       public, the segmentation is not, and there is no anonymous access. The notebook's own
       token cell reads a saved CAVE token and hands it to every CloudVolume(SEG...) call; with
       this flag false, that cell prints one line and does nothing.

       The token is NEVER written here. It is fetched inside the Colab session, so a notebook
       file passed to somebody else carries no credential -- which is why this is a boolean and
       not a string. */
    /* ── WHERE THE SEGMENTATION IS, RELATIVE TO THE EM ────────────────────────────────────
       Zero everywhere but cb2, which publishes its segmentation 1,216 sections below its EM.
       χJump has carried that number as UJ.cfg.volume.segTranslateZ since 2026-08-30, for the
       Neuroglancer links; the notebook needs the same fact in nanometres, and the sign is the
       other way round because the page MOVES THE SOURCE UP to the tissue while the notebook
       READS DOWN from a point on the tissue. */
    lines.push("SEG_OFFSET_NM = " + JSON.stringify(opts.segOffsetNm || [0, 0, 0]));
    /* Candidate mesh sources, tried in order; empty means the segmentation volume's own. Only
       cb2 needs it: its meshes are a separate store, and reading them off the segmentation
       returned the handful of ids the two stores happen to share. */
    lines.push("MESH_SRC = " + JSON.stringify((opts.meshSources || [])
                                              .map(toCloudVolumePath).filter(Boolean)));
    lines.push("SEG_CAVE_AUTH = " + pyBool(opts.segCaveAuth === true));
    /* ── THE TOKEN, ONLY IF THE USER TICKED THE BOX ────────────────────────────────────────
       Søren asked for it and it is off by default, because it changes what the downloaded file
       IS: a .ipynb with a live CAVE credential in it, which sits in Downloads and travels with
       the file if it is ever shared. Unticked, nothing is written here and the notebook fetches
       the token inside Colab, where it never touches disk.

       The warning goes ABOVE the value, so the first thing anybody reading or sharing this
       notebook sees is what is in it. */
    if (opts.caveToken && opts.segCaveAuth === true) {
      lines.push("");
      lines.push("# " + "!".repeat(76));
      lines.push("# THIS NOTEBOOK CONTAINS YOUR CAVE TOKEN. It was put here because the box was");
      lines.push("# ticked in the tool. Treat this file as a credential: do not share it, do not");
      lines.push("# commit it, delete it when the run is done. Untick the box to have Colab ask");
      lines.push("# for the token instead, in which case nothing sensitive is written to disk.");
      lines.push("# " + "!".repeat(76));
      lines.push("CAVE_TOKEN = " + pyStr(opts.caveToken));
      lines.push("");
    }
    /* Set here as well as in the token cell, because THIS cell is the one that gets rewritten:
       a name the later cells read and this one never sets is a NameError, and the plan cell
       catches Exception, so it would surface as an unexplained "seg mip None". */
    lines.push("SEG_SECRETS = None");
    lines.push("");
    lines.push("# FINEST FIRST. This read [3, 2, 1, 0] with a rule of 'keep the first level");
    lines.push("# under the vertex budget' -- and level 3 is the coarsest, so it always was, and");
    lines.push("# every cell came out at the lowest resolution the dataset has. The fetch cell");
    lines.push("# probes level 3, predicts the finer levels from it, and takes the finest that");
    lines.push("# fits. Raise the budgets for a sharper cell; the download grows with them.");
    lines.push("LOD_PREFERENCE = [0, 1, 2, 3]");
    lines.push("VERTEX_BUDGET       = 2_000_000   # per cell");
    lines.push("VERTEX_BUDGET_TOTAL = 8_000_000   # across the whole export");
    lines.push("");
    lines.push("# ── the box, and what it is allowed to cost ──────────────────────────────────");
    lines.push("EM_MAX_PX       = 1024    # longest in-plane side of a written section");
    lines.push("EM_MAX_SECTIONS = 120     # frames in each sweep");
    lines.push("EM_MAX_MB       = 400     # over the wire, uncompressed uint8");
    lines.push("OVERLAY_OPACITY = 0.35");
    lines.push("");
    /* ── EVERY NAME THE OTHER CELLS READ ──────────────────────────────────────────────────
       This cell REPLACES the notebook's own params cell, so anything the later cells need and
       this list forgets is a NameError at runtime. That is not hypothetical: the vasculature
       section shipped before VASC/VASC_IDS/VASC_* were added here, and because that section
       catches Exception and carries on, the only sign was a scene with no vessels in it and one
       line of output nobody was looking for. notebookcheck.py now asserts this list covers every
       capitalised global the other cells reference. */
    /* EMPTY unless the page names one. The TriSAM segmentation is minnie65's; hard-coding it as
       a default meant every other dataset's notebook carried a source that does not overlap its
       own volume, which would have fetched a box of nothing and reported it as an empty box. */
    lines.push("VASC = " + pyStr(toCloudVolumePath(opts.vascSource || "")));
    /* ── HAND-TRACED STRUCTURES ────────────────────────────────────────────  2026-09-16
       Section 4b reads this. The NOTEBOOK's own params cell has carried `TRACINGS = []` since the
       day that section landed; THIS cell replaces that one, and for its first day it did not,
       which is a NameError on the first run of every notebook the panel writes.

       Written in trace_mesh.py's own key names -- name/type/traced_by/color/nucleus_id/rings --
       so a structure read out of the sheet by core/tracing.js goes straight in with nothing
       translating it a second time. */
    var tracings = Array.isArray(opts.tracings) ? opts.tracings : [];
    lines.push("# Cells the segmentation does not have, outlined section by section by a person.");
    lines.push("# Section 4b meshes each of these and appends it to CELLS as an ordinary cell.");
    if (!tracings.length){
      lines.push("TRACINGS = []");
    } else {
      lines.push("TRACINGS = [");
      tracings.forEach(function(t){
        lines.push("    {'name': " + pyStr(t.name || "traced")
                   + ", 'kind': " + pyStr(t.kind || "")
                   + ", 'type': " + pyStr(t.type || "traced")
                   + ", 'traced_by': " + pyStr(t.traced_by || "")
                   + (t.color ? ", 'color': " + pyStr(t.color) : "")
                   + (t.nucleus_id ? ", 'nucleus_id': " + pyStr(String(t.nucleus_id)) : "")
                   + ",");
        lines.push("     'rings': [");
        (t.rings || []).forEach(function(r){
          lines.push("         {'z': " + Math.round(Number(r.z)) + ", 'points': ["
                     + (r.points || []).map(function(p){
                         return "[" + Math.round(Number(p[0])) + "," + Math.round(Number(p[1])) + "]";
                       }).join(",") + "]},");
        });
        lines.push("     ]},");
      });
      lines.push("]");
    }
    lines.push("");
    lines.push("VASC_IDS   = None    # None = any non-zero label; [1] = only the segment uJump selects");
    lines.push("VASC_COLOR = " + pyStr((opts.brand && opts.brand.vasc) || "#b03a48"));
    lines.push("VASC_ALPHA = 0.30");
    lines.push("VASC_EXTENT = " + pyStr(opts.vascExtent === "whole" ? "whole" : "box"));
    lines.push("VASC_MAX_PX       = 512");
    lines.push("VASC_MAX_SECTIONS = 512");
    lines.push("VASC_MAX_MB       = 250");
    lines.push("VASC_STEP         = 1");
    lines.push("");
    /* Mesh vertex units -> nanometres. Identity for the ordinary precomputed sources; CB2's page
       carries [[0,0,1e9],[0,1e9,0],[1e9,0,0]] because its vertices are METRES on permuted axes,
       and that constant is copied from the page rather than re-derived -- it was got wrong twice
       when it was reasoned about. */
    const M = opts.meshVertexToNm;
    lines.push("MESH_VERTEX_TO_NM = " + (Array.isArray(M) && M.length === 3
      ? "[" + M.map(r => "[" + r.map(pyNum).join(", ") + "]").join(", ") + "]"
      : "[[1, 0, 0], [0, 1, 0], [0, 0, 1]]"));
    lines.push("");
    /* The wordmark drawn bottom-right in the video. Dark-theme colours whatever the page's own
       theme is: the render's background is #0d1117 either way. */
    /* WHAT THE FILES ARE CALLED. Søren, 2026-09-09: "the files are called microns for all of
       them, but microns dataset is specifically uJump." Derived from the tool's own wordmark, in
       the transliteration he writes the tools in -- βJump -> bjump, χJump -> xjump, µJump ->
       ujump -- so a folder of downloads says which tool made each one. */
    const GREEK = {"\u00b5": "u", "\u03bc": "u", "\u03b2": "b", "\u03c7": "x", "\u03b4": "d",
                   "\u03b7": "h", "\u03bb": "l", "\u03c0": "p", "\u03c9": "w"};
    function outName(o){
      var raw = String(((o.brand || {}).name) || o.datasetId || "cells");
      var s = "";
      for (var i = 0; i < raw.length; i++)
        s += GREEK[raw[i]] !== undefined ? GREEK[raw[i]] : raw[i];
      s = s.toLowerCase().replace(/[^a-z0-9]+/g, "_").replace(/^_+|_+$/g, "");
      return (s || "cells") + "_cells";
    }

    const br = opts.brand || {};
    /* `name` is the TOOL's -- the page's own <h1 class="logo"> -- and NOT opts.datasetLabel,
       which is "MICrONS minnie65" here. That is the dataset, and it now has its own line. */
    lines.push("OUT_NAME = " + pyStr(outName(opts)));
    lines.push("");
    lines.push("BRAND = {'name': " + pyStr(br.name || "\u00b5Jump")
               + ", 'url': " + pyStr(br.url || "www.grubblab.com")
               + ",");
    lines.push("         'dataset': " + pyStr(br.dataset || opts.datasetLabel || "") + ",");
    lines.push("         'accent': " + pyStr(br.accent || "#27e0b3")
               + ", 'ink': " + pyStr(br.ink || "#e6edf3")
               + ", 'mut': " + pyStr(br.mut || "#8b949e") + "}");
    lines.push("");
    lines.push("EM_BOX_MODE    = 'manual'          # the box you drew, not a guess around a cell");
    lines.push("EM_BOX_SIZE_UM = (60.0, 60.0, 30.0)");
    lines.push("EM_BOX_UM      = " + box);
    /* Nanometres per voxel, so the notebook can put the box centre on the video in the voxel
       coordinates the pages and Neuroglancer use. The page knows it; Blender never does.
       2026-09-09. */
    const R = opts.resNm;
    lines.push("RES_NM         = " + (Array.isArray(R) && R.length === 3
      ? "[" + R.map(pyNum).join(", ") + "]" : "None"));
    lines.push("");
    lines.push("on = [k for k, v in INCLUDE.items() if v]");
    /* Plain concatenation rather than an f-string: an f-string with single quotes containing a
       single-quoted subscript only became legal in Python 3.12, and this notebook should not care
       which Python the runtime happens to be. */
    lines.push("print(str(len(CELLS)) + ' cells: ' "
               + "+ ', '.join(sorted(set(c['type'] for c in CELLS))))");
    lines.push("print('including: ' + (', '.join(on) if on else 'NOTHING -- tick something'))");
    return lines.join("\\n");
  }

  function buildNotebook(opts){
    const nb = JSON.parse(NB_SOURCE);
    let replaced = 0;
    nb.cells = nb.cells.map(c => {
      if (c.metadata && c.metadata.ujump === "params"){
        replaced++;
        return Object.assign({}, c, {source: srcLines(paramsCell(opts))});
      }
      /* Everything else verbatim, only re-shaped from one string into Jupyter's line array. */
      return Object.assign({}, c, {source: srcLines(c.source)});
    });
    if (replaced !== 1){
      /* Loud rather than silent: a notebook whose parameters were not substituted would run
         against the TEST cells and the test box, and look perfectly plausible doing it. */
      throw new Error("blenderexport: expected 1 params cell, replaced " + replaced);
    }
    nb.metadata = Object.assign({}, nb.metadata, {
      colab: {name: filenameFor(opts), provenance: []}
    });
    return nb;
  }

  function filenameFor(opts){
    return (opts.datasetId || "region") + "_"
      + String(opts.boxLabel || "box").replace(/\\s+/g, "_") + "_blender.ipynb";
  }

  function downloadNotebook(opts){
    const nb = buildNotebook(opts);
    const filename = filenameFor(opts);
    const blob = new Blob([JSON.stringify(nb, null, 1)], {type: "application/x-ipynb+json"});
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url; a.download = filename;
    document.body.appendChild(a); a.click(); document.body.removeChild(a);
    setTimeout(() => URL.revokeObjectURL(url), 1000);
    return filename;
  }

  return {buildNotebook, downloadNotebook, filenameFor, brandFromPage};
})();
''' % NB_JSON

io.open(OUT, "w", encoding="utf-8").write(JS)
print("wrote %s\n  %d notebook cells embedded, %.0f KB"
      % (OUT, len(nb["cells"]), len(JS) / 1024.0))
