# -*- coding: utf-8 -*-
u"""The cell with no soma: δJump was skipping every proofread fragment.         2026-09-20

Søren, on δJump's new Show in 3D: *"It seems like the segmentations nearest to the soma are missing
from the show in 3d. Why is that happening, have they saved the somas differently?"*

Yes — but not because they are somas.

── MEASURED, ON THE REAL CELL ──────────────────────────────────────────────────

Nucleus 352780, root 864691132746251725, fetched through the page's own `UJ.mesh.fetchCombinedMesh`
and the vertices counted against the nucleus centroid:

    1,956,649 vertices over a 366 x 332 x 382 µm box
    vertices within 15 µm of the nucleus centre :   507
    vertices within 10 µm of the nucleus centre :     0
    vertices within  5 µm of the nucleus centre :     0

A soma-shaped hole, centred on the nucleus, in a cell with nearly two million vertices everywhere
else. Not a rendering effect and not a transparency effect — the geometry is not there.

── V1DD'S MESH MANIFEST HAS TWO KINDS OF FRAGMENT ──────────────────────────────

    274 fragments for this root
    271 like  ~168682608106930366:2:168682608106930176:366083086-0.shard:1
      3 like  527202631380040418:0:81920-90112_32768-40960_0-16384

The first kind are **initial** meshes: baked once, for parts of the segmentation nothing has
edited, and packed into shard files under `graphene_meshes/initial/<layer>/`. The second kind are
**dynamic** meshes: generated by the meshing service for supervoxels that PROOFREADING HAS
CHANGED, and written as plain objects under `graphene_meshes/dynamic/`.

**The soma is the part of a neuron proofreaders touch most.** Split a merge, join a fragment, fix a
false split — it happens at the cell body, because that is where the errors are and where the
dendrites meet. So the soma's mesh is a dynamic fragment on almost any proofread cell, and the rest
of the arbor stays initial. That is the whole of the answer to "have they saved the somas
differently": not the somas, the EDITS, and the soma is where the edits are.

── AND THE CODE SAID SO ALL ALONG ──────────────────────────────────────────────

core/mesh.js already split the manifest into `initial` and `dynamic`, and then:

    let totalVerts=0,totalIdx=0,decoded=0,failed=dynamic.length,bytes=0;

**counted every dynamic fragment as failed before trying any of them**, and told the user so in a
parenthesis nobody reads during a progress bar:

    "(" + dynamic.length + " too freshly edited to fetch yet)"

"Yet" was written when nothing knew where those objects lived. They live one path segment away, and
they are public: an anonymous GET of
`…/graphene_meshes/dynamic/527202631380040418:0:81920-90112_32768-40960_0-16384` returns 206, and
its first five bytes are **DRACO** — the same encoding as the sharded ones, decodable by the
decoder this function has already loaded. 1.7 MB for all three.

So: fetch them, with the decoder that is already open, before it is destroyed.

GUARDED ON A CONFIG KEY, so this changes nothing anywhere else. δJump is the only page in the
family with a `manifestBase` at all — the graphene path is its alone — but a page that does not
name a dynamic base keeps exactly today's behaviour, including the parenthesis.

Run: python3 src/the_soma_is_the_part_that_was_edited.py
"""
import io
import os

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def edit(rel, pairs, marker=None):
    p = os.path.join(HERE, rel)
    s = io.open(p, encoding="utf-8").read()
    if marker and marker in s:
        for name, _o, _n in pairs:
            print("  already there: " + name)
        return
    before = s
    for name, old, new in pairs:
        if new in s and (old not in s or old in new):
            print("  already there: " + name)
            continue
        n = s.count(old)
        assert n == 1, "%s / %s: anchor found %d times" % (rel, name, n)
        s = s.replace(old, new, 1)
        print("  ok: " + name)
    if s != before:
        io.open(p, "w", encoding="utf-8").write(s)


# ── 1. say what is happening, not that it cannot be done ──────────────────────────────────────
SAY_OLD = u'''    onProgress&&onProgress(0.05,initial.length+" fragment(s)\u2026"+(dynamic.length?(" ("+dynamic.length+" too freshly edited to fetch yet)"):""));'''
SAY_NEW = u'''    const dynBase=CFG.meshBaseDynamic||"";
    onProgress&&onProgress(0.05,initial.length+" fragment(s)\u2026"
      +(dynamic.length?(" + "+dynamic.length+(dynBase?" edited":" too freshly edited to fetch yet")):""));'''

# ── 2. fetch them, with the decoder that is already open ──────────────────────────────────────
LOOP_OLD = u'''    draco.destroy(decoder);
    if(!decoded)throw new Error("no fragments decoded ("+initial.length+" in the manifest, "+failed+" failed)");'''

LOOP_NEW = u'''    /* \u2500\u2500 THE FRAGMENTS PROOFREADING HAS TOUCHED \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500  2026-09-20
       S\u00f8ren: *"the segmentations nearest to the soma are missing from the show in 3d ... have they
       saved the somas differently?"* Measured on root 864691132746251725: 1,956,649 vertices over
       a 366 \u00b5m box and ZERO of them within 10 \u00b5m of the nucleus centre. A soma-shaped hole.

       V1DD's manifest carries two kinds of fragment. `initial` meshes are baked into the shards
       above, for segmentation nothing has edited. `dynamic` meshes are generated by the meshing
       service for supervoxels PROOFREADING HAS CHANGED, and written as plain objects one path
       segment away. **The soma is where proofreaders work** \u2014 splits and merges happen where the
       dendrites meet \u2014 so on a proofread cell the soma is dynamic and the arbor is initial.

       This counted them as failed before trying any of them, and said "too freshly edited to
       fetch yet" in a progress line nobody reads. "Yet" was written when nothing knew where they
       lived. They are public, they are DRACO like the others, and the decoder is still open. */
    if(dynBase&&dynamic.length){
      failed-=dynamic.length;                       // they were failed before they were attempted
      for(let i=0;i<dynamic.length;i++){
        let blob;
        try{
          const r=await fetch(dynBase+dynamic[i]);
          if(!r.ok)throw new Error("HTTP "+r.status);
          blob=new Uint8Array(await r.arrayBuffer());
        }catch(_e){ failed++; continue; }
        bytes+=blob.length;
        let d;
        try{ d=decodeDracoFragment(draco,decoder,blob); }catch(_e){ failed++; continue; }
        const base=totalVerts/3;
        if(base)for(let k=0;k<d.idx.length;k++)d.idx[k]+=base;
        for(let k=0;k<d.verts.length;k++)d.verts[k]=d.verts[k]/1000;   // nm -> µm, as above
        vertChunks.push(d.verts);idxChunks.push(d.idx);
        totalVerts+=d.verts.length;totalIdx+=d.idx.length;decoded++;
        onProgress&&onProgress(0.96,"fetching+decoding edited "+(i+1)+"/"+dynamic.length+"\u2026");
        await breathe();
      }
    }
    draco.destroy(decoder);
    if(!decoded)throw new Error("no fragments decoded ("+(initial.length+dynamic.length)+" in the manifest, "+failed+" failed)");'''

print("core/mesh.js")
edit("core/mesh.js", [
    (u"the progress line stops saying it cannot", SAY_OLD, SAY_NEW),
    (u"the edited fragments are fetched and decoded", LOOP_OLD, LOOP_NEW),
], marker=u"THE FRAGMENTS PROOFREADING HAS TOUCHED")


# ── 3. δJump says where they live ─────────────────────────────────────────────────────────────
CFG_OLD = u'''  meshBase:"https://storage.googleapis.com/v1dd_pcg/ws/graphene_meshes/initial/",'''
CFG_NEW = u'''  meshBase:"https://storage.googleapis.com/v1dd_pcg/ws/graphene_meshes/initial/",
  /* WHERE THE EDITED FRAGMENTS LIVE.  2026-09-20
     The manifest for a proofread root mixes two kinds: `~<id>:<layer>:…shard:<n>` initial meshes,
     baked into the shards above, and plain `<id>:0:<x0-x1>_<y0-y1>_<z0-z1>` DYNAMIC meshes,
     generated for supervoxels proofreading has changed. core/mesh.js used to count the second
     kind as failed without trying, which took the SOMA off every proofread cell — that is where
     the edits are. Same bucket, same Draco encoding, one path segment along, and public: an
     anonymous GET returns 206 with no token. */
  meshBaseDynamic:"https://storage.googleapis.com/v1dd_pcg/ws/graphene_meshes/dynamic/",'''

print("\ndjump.html")
edit("djump.html", [
    (u"δJump names the dynamic mesh base", CFG_OLD, CFG_NEW),
], marker=u"meshBaseDynamic:")

print(u"\nnow: re-run the soma probe on the live page and check vertsWithin10um > 0")
