# -*- coding: utf-8 -*-
u"""The organelle locations fold up.                                             2026-09-19

Søren: *"This is getting out of hand. We need to have the details in an expandable menu, where they
are written in a more organised manner."*

What his microglia panel says, as one paragraph:

    6 users have logged organelle locations for this cell — 6× lysosome (Volumetric centre of the
    outlined "Lysosome" (3.39 µm³, 20 sections), registered from the segmentation rather than
    placed by hand.; Volumetric centre of the outlined "Lysosome 1" (3.39 µm³, 20 sections),
    registered from the segmentation rather than placed by hand.; ... )

Six sentences that differ in three words each, joined with "; ", inside brackets, on one line.

THREE THINGS ARE WRONG AND ONLY ONE OF THEM IS THE LENGTH.

  "6 USERS" IS ONE USER. `organelleGroups.length` counts SUBMISSIONS, and the line has always
  called them users. Six of these are his own, so the panel is telling him six people agree with
  him about where his own lysosomes are. Counted by distinct reporter now, and when nobody is named
  it says how many LOCATIONS there are rather than inventing people.

  THE COMMENT WAS NEVER MEANT TO BE READ IN BULK. It is written for a row of a spreadsheet, where
  one of them is a full and useful sentence. Six of them in a paragraph is the same information
  with the structure taken out, and the structure is the part that was doing the work: which
  organelle, how big, where. So the row carries those as COLUMNS, and the sentence stays in the
  sheet where it reads properly.

  THE ROWS WERE ALREADY THERE, below the paragraph, saying "Lysosome at (295844, 151391, 17862)".
  So the panel printed everything twice, in two shapes, and the better of the two was the one
  underneath. They move inside the fold and gain what the prose had that they did not: the name it
  was outlined under and its size.

PARSED FROM OUR OWN SENTENCE, and said out loud because parsing prose is usually a smell. The text
is generated by tracingRegisterCentre in this project, three files away; the row's own columns do
not carry the volume. A tolerant regex reads back what we wrote, and every part of the row that
cannot be read is simply left out rather than guessed at -- a row that says less is a row, and a
row that says something invented is a bug.

Run: python3 src/the_organelle_locations_fold_up.py
"""
import io
import os

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

ROWS = [
    (u'''function organelleStructRowsHtml(structs){''',
     u'''/* ── WHAT AN OUTLINE'S CENTRE ROW SAYS ─────────────────────────────────────────  2026-09-19
   Søren: *"We need to have the details in an expandable menu, where they are written in a more
   organised manner."*

   The size and the name it was outlined under live only in the comment -- the row's own columns
   never carried them -- and that comment is written by tracingRegisterCentre in this project, so
   this is reading back our own sentence rather than somebody else's prose. Anything it cannot read
   is left out: a shorter row is a row, an invented one is a bug. */
function organelleCentreBits(comment){
  var s = String(comment || "");
  if (!/registered from the segmentation/i.test(s)) return null;
  var out = { name: "", size: "", sections: "" };
  var m = /outlined\\s+[\\u201c"]([^\\u201d"]+)[\\u201d"]/.exec(s);
  if (m) out.name = m[1];
  var v = /\\(([\\d.eE+-]+)\\s*\\u00b5m\\u00b3(?:,\\s*(\\d+)\\s*sections?)?\\)/.exec(s);
  if (v){ out.size = v[1]; out.sections = v[2] || ""; }
  return out;
}
function organelleStructRowsHtml(structs){''',
     "an outline's own row can say what it is and how big"),

    (u'''    return pa?'<div class="meta" style="margin-top:4px">'+capLabel+' at ('+coordSpan(pa[0],pa[1],pa[2])+')'+jumpBtn(pa)+'</div>':"";''',
     u'''    if(!pa)return"";
    /* ONE ROW, IN COLUMNS: what it is, how big it is, where it is. The paragraph this replaces had
       all three and no shape; six of them had three shapes and no paragraph anybody could read. */
    const bits=organelleCentreBits(s.comment);
    const named=(bits&&bits.name)?bits.name:capLabel;
    const size=(bits&&bits.size)
      ?('<span class="hint" style="margin-left:8px">'+bits.size+' \\u00b5m\\u00b3'
        +(bits.sections?(' \\u00b7 '+bits.sections+' sections'):'')+'</span>')
      :'';
    /* Where it came from, once, quietly. A centre computed from an outline is a different KIND of
       claim from a point somebody placed by eye, and the panel already prefers the first. */
    const from=(bits||/segment/i.test(String(s.source||"")))
      ?'<span class="hint" style="margin-left:8px">from the outline</span>'
      :(s.by?'<span class="hint" style="margin-left:8px">by '+escHtml(String(s.by))+'</span>':'');
    return '<div class="meta" style="margin-top:4px;display:flex;align-items:baseline;gap:4px;'
      +'flex-wrap:wrap"><span>'+escHtml(named)+'</span>'+size+from
      +'<span style="flex:1 1 auto"></span><span>('+coordSpan(pa[0],pa[1],pa[2])+')</span>'
      +jumpBtn(pa)+'</div>';''',
     "...instead of a coordinate and nothing else"),
]

SUMMARY = [
    (u'''        const allStructs=[].concat(...organelleGroups.map(g=>(g.structures||[]).map(s=>({kind:s.kind,pointA:s.pointA,pointB:s.pointB}))));
        const parts=organelleCountParts(allStructs);
        const comments=organelleGroups.filter(g=>g.comment).map(g=>g.comment);
        html+=(html?"<br>":"")+'<span style="color:var(--accent)">&#128172; '+organelleGroups.length+' '+(organelleGroups.length>1?"users have":"user has")+' logged organelle locations for this cell'+(parts.length?" &mdash; "+parts.join(", "):"")+(comments.length?" ("+comments.join("; ")+")":"")+'.</span>';
        organRowsHtml=organelleStructRowsHtml(allStructs);''',
     u'''        /* The comment travels WITH its structure now rather than being swept into a paragraph
           at the end: it is what the row reads its name and size out of. subCount is 1 for every
           one of these, so a group is a structure. */
        const allStructs=[].concat(...organelleGroups.map(g=>(g.structures||[]).map(s=>({
          kind:s.kind,pointA:s.pointA,pointB:s.pointB,
          comment:s.comment||g.comment||"",source:s.source||"",by:s.by||g.by||""}))));
        const parts=organelleCountParts(allStructs);
        /* ── SIX SENTENCES BECOME SIX ROWS, BEHIND A FOLD ────────────────────────  2026-09-19
           Søren: *"This is getting out of hand. We need to have the details in an expandable menu,
           where they are written in a more organised manner."*

           And "6 users" was one user: this counted SUBMISSIONS and called them users, so a person
           who had outlined six of their own lysosomes was told six people agreed with them. Named
           reporters are counted when there are any; when there are none the line counts LOCATIONS,
           which is the thing it actually knows. */
        const who={};
        allStructs.forEach(function(s){ if(s.by)who[String(s.by)]=1; });
        const nWho=Object.keys(who).length;
        const head=nWho
          ? (nWho+' '+(nWho>1?'people have':'person has')+' logged organelle locations for this cell')
          : (allStructs.length+' organelle location'+(allStructs.length===1?'':'s')
             +' for this cell');
        html+=(html?"<br>":"")
          +'<details class="rv-panel" style="margin-top:6px"><summary style="color:var(--accent)">'
          +'&#128172; '+head+(parts.length?" &mdash; "+parts.join(", "):"")+'</summary>'
          +'<div style="margin-top:4px">'+organelleStructRowsHtml(allStructs)+'</div></details>';
        /* The rows used to be printed BELOW the paragraph as well, so everything appeared twice in
           two shapes. They are inside the fold now and nowhere else. */
        organRowsHtml="";''',
     "the locations fold up, one organised row each"),
]


def edit(rel, pairs):
    p = os.path.join(HERE, rel)
    s = io.open(p, encoding="utf-8").read()
    print(rel)
    for old, new, why in pairs:
        if new in s and (old not in s or old in new):
            print("  already there: " + why)
            continue
        assert not (new in s and old in s), "AMBIGUOUS: " + why
        assert old in s, "NOT FOUND: " + why
        assert s.count(old) == 1, "ambiguous (%d): %s" % (s.count(old), why)
        s = s.replace(old, new, 1)
        print("  ok: " + why)
    io.open(p, "w", encoding="utf-8").write(s)


edit("core/panel.js", ROWS + SUMMARY)
print("\nnow: node organlinescheck.js && node ccpanelcheck.js && python3 src/build_stamps.py")
